
import { Clue } from './types';

const IMAGE_DATA: { [key: string]: string } = {
  "A-1": "https://i.ibb.co/0ywCTd5x/A-1.jpg",
  "A-2": "https://i.ibb.co/TM5gGxHp/A-2.jpg",
  "A-3": "https://i.ibb.co/Xf0BpYK1/A-3.jpg",
  "A-4": "https://i.ibb.co/xqJtDs7y/A-4.jpg",
  "A-5": "https://i.ibb.co/VptPWxkW/A-5.jpg",
  "A-6": "https://i.ibb.co/yc3gLPn8/A-6.jpg",
  "A-7": "https://i.ibb.co/pj8D8pt8/A-7.jpg",
  "A-8": "https://i.ibb.co/NnkfWtjQ/A-8.jpg",
  "A-9": "https://i.ibb.co/rRcWbMTM/A-9.jpg",
  "A-10": "https://i.ibb.co/GQSbDgD6/A-10.jpg",
  "A-11": "https://i.ibb.co/PGbhbqz4/A-11.jpg",
  "A-12": "https://i.ibb.co/LXPNnV7L/A-12.jpg",
  "A-13": "https://i.ibb.co/FqscJBvx/A-13.jpg",
  "A-14": "https://i.ibb.co/LXZW7K7x/A-14.jpg",
  "A-15": "https://i.ibb.co/Xwqp9DB/A-15.jpg",
  "A-16": "https://i.ibb.co/FqjXkWD3/A-16.jpg",
  "A-17": "https://i.ibb.co/xK0f9MzC/A-17.jpg",
  "A-18": "https://i.ibb.co/qL1rVbkt/A-18.jpg",
  "B-1": "https://i.ibb.co/m56VvznR/B-1.jpg",
  "B-2": "https://i.ibb.co/dwpVWb8x/B-2.jpg",
  "B-3": "https://i.ibb.co/TDDBsXVh/B-3.jpg",
  "B-4": "https://i.ibb.co/Xx5P71TV/B-4.jpg",
  "B-5": "https://i.ibb.co/V04ZJGXT/B-5.jpg",
  "B-6": "https://i.ibb.co/fd0PZCqL/B-6.jpg",
  "B-7": "https://i.ibb.co/KpLhxkhY/B-7.jpg",
  "B-8": "https://i.ibb.co/sJq2qZYm/B-8.jpg",
  "B-9": "https://i.ibb.co/FbM0rfhv/B-9.jpg",
  "B-10": "https://i.ibb.co/XrYbsDHm/B-10.jpg",
  "B-11": "https://i.ibb.co/4ndR95nT/B-11.jpg",
  "B-12": "https://i.ibb.co/Z6HjjXrt/B-12.jpg",
  "B-13": "https://i.ibb.co/S4xV18cG/B-13.jpg",
  "B-14": "https://i.ibb.co/b5pQv7m4/B-14.jpg",
  "B-15": "https://i.ibb.co/WvCW92Fk/B-15.jpg",
  "B-16": "https://i.ibb.co/G38mqDvM/B-16.jpg",
  "B-17": "https://i.ibb.co/bgJBd2sz/B-17.jpg",
  "B-18": "https://i.ibb.co/W4kzbSkL/B-18.jpg",
  "C-1": "https://i.ibb.co/Nn3bXbsF/C-1.jpg",
  "C-2": "https://i.ibb.co/LDXHB5rN/C-2.jpg",
  "C-3": "https://i.ibb.co/JWjNq4t0/C-3.jpg",
  "C-4": "https://i.ibb.co/spMLD9jY/C-4.jpg",
  "C-5": "https://i.ibb.co/chBqmMn4/C-5.jpg",
  "C-6": "https://i.ibb.co/xtzmqgrM/C-6.jpg",
  "C-7": "https://i.ibb.co/99CkcLJC/C-7.jpg",
  "C-8": "https://i.ibb.co/zhfsPmFS/C-8.jpg",
  "C-9": "https://i.ibb.co/hxPHRYF8/C-9.jpg",
  "C-10": "https://i.ibb.co/84QxQqr8/C-10.jpg",
  "C-11": "https://i.ibb.co/RTLTsCqF/C-11.jpg",
  "C-12": "https://i.ibb.co/pjLDNQWV/C-12.jpg",
  "C-13": "https://i.ibb.co/39vwMqvL/C-13.jpg",
  "C-14": "https://i.ibb.co/7d3Vk9RY/C-14.jpg",
  "C-15": "https://i.ibb.co/Gv1stdXg/C-15.jpg",
  "C-16": "https://i.ibb.co/QFZRR7Kk/C-16.jpg",
  "C-17": "https://i.ibb.co/cKHj7sHv/C-17.jpg",
  "C-18": "https://i.ibb.co/jC62tRm/C-18.jpg",
  "D-1": "https://i.ibb.co/ZRYzc6wX/D-1.jpg",
  "D-2": "https://i.ibb.co/F4bgqG8K/D-2.jpg",
  "D-3": "https://i.ibb.co/MkcFp3tH/D-3.jpg",
  "D-4": "https://i.ibb.co/k2YjBLk9/D-4.jpg",
  "D-5": "https://i.ibb.co/TB3LJqQM/D-5.jpg",
  "D-6": "https://i.ibb.co/JjgtvTXW/D-6.jpg",
  "D-7": "https://i.ibb.co/VcTL81kg/D-7.jpg",
  "D-8": "https://i.ibb.co/dsK7Y42J/D-8.jpg",
  "D-9": "https://i.ibb.co/MDhv0jFP/D-9.jpg",
  "D-10": "https://i.ibb.co/m5PsYNQx/D-10.jpg",
  "D-11": "https://i.ibb.co/dsz1tc2q/D-11.jpg",
  "D-12": "https://i.ibb.co/nX5V5kJ/D-12.jpg",
  "D-13": "https://i.ibb.co/mrfDTZHX/D-13.jpg",
  "D-14": "https://i.ibb.co/JwPzh2rn/D-14.jpg",
  "D-15": "https://i.ibb.co/jZR7pHS9/D-15.jpg",
  "D-16": "https://i.ibb.co/bMd7XR79/D-16.jpg",
  "D-17": "https://i.ibb.co/7xQsfTsB/D-17.jpg",
  "D-18": "https://i.ibb.co/Ld6dGcfy/D-18.jpg"
};

export const CLUES: Clue[] = Object.keys(IMAGE_DATA).map(label => ({
  id: label,
  label: label,
  imageUrl: IMAGE_DATA[label]
}));

export const PHASE_DURATION = {
  TEAM_ANALYSIS: 300,
  INFO_EXCHANGE: 300,
  FINAL_SUBMIT: 600
};
